### ISSUE TITLE
👋🏼 Hola! 

### ISSUE THREAD

**Issue by vinjatovix** [Nuriarique/Coco#1]
Te veo on fire practicando con los repos 🤘🏼🤘🏼🤘🏼  Felicidades. 

Acuérdate de separar en el HTML el documento como head y body. 

Esta es la primera vez q abro un issue así q no se como va esto 😂.

**Comment by Nuriarique** [comment]
acabo de verlo! jaja 
era una prueba para ver si podía guardar un .html
